[features]
seeds = true
skip-lint = false
[programs.localnet]
solsend_core = "4FF8j7wY3uxZPbKKRA6RYzmpfkPnbvxGvWxNaBLeino5"
[programs.devnet]
solsend_core = "4FF8j7wY3uxZPbKKRA6RYzmpfkPnbvxGvWxNaBLeino5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet" # This should be `devnet` when deploying to devnet
wallet = "/Users/antarikshverma/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
